---

- name: GLPI
  block:


    - name: Init GLPI Session
      ansible.builtin.include_tasks:
        file: tasks/glpi/init-session.yaml


    - name: "[TRACE] Inbound data from netbox"
      ansible.builtin.debug:
        msg: "{{ netbox }}"


    - name: GLPI Item
      ansible.builtin.include_tasks:
        file: tasks/glpi/crud.yaml


  always:


    - name: Kill GLPI Session
      ansible.builtin.include_tasks:
        file: tasks/glpi/kill-session.yaml
