---

- name: Check Required Fields
  ansible.builtin.assert:
    that:
      - nfc_role_netbox_kubernetes_database_password is defined
      - nfc_role_netbox_kubernetes_database_password != ''
      - nfc_role_netbox_kubernetes_database_host is defined
      - nfc_role_netbox_kubernetes_database_host != ''
      - nfc_role_netbox_kubernetes_redis_database is defined
      - nfc_role_netbox_kubernetes_redis_database != ''
      - nfc_role_netbox_kubernetes_redis_cache_database is defined
      - nfc_role_netbox_kubernetes_redis_cache_database != ''
    msg: "You are missing a required field"


- name: Create Namespace
  kubernetes.core.k8s:
    apply: true
    name: "{{ nfc_role_netbox_kubernetes_namespace }}"
    kind: Namespace
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
    state: present
  become: true
  diff: true


- name: Add Secret
  kubernetes.core.k8s:
    apply: true
    template: secret.yaml.j2
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
    state: present
  become: true
  diff: false
  no_log: >
    {%- if not nfc_pb_netbox_force_logging | default(false) -%}
      true
    {%- else -%}
      false
    {%-endif %}


- name: Add ConfigMap
  kubernetes.core.k8s:
    apply: true
    template: configmap.yaml.j2
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
    state: present
  become: true
  diff: true


- name: Deploy Redis
  kubernetes.core.k8s:
    apply: true
    template: deployment-redis.yaml.j2
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
    state: present
  become: true
  diff: true


- name: Redis Service
  kubernetes.core.k8s:
    apply: true
    template: service-redis.yaml.j2
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
    state: present
  become: true
  diff: true


- name: Add PVC
  kubernetes.core.k8s:
    apply: true
    template: pvc.yaml.j2
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
    state: present
  become: true
  diff: true


- name: Deploy NetBox
  kubernetes.core.k8s:
    apply: true
    template: deployment.yaml.j2
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
    state: present
  become: true
  diff: true


- name: NetBox Service
  kubernetes.core.k8s:
    apply: true
    template: service.yaml.j2
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
    state: present
  become: true
  diff: true
