---

- name: Load PostgreSQL Secrets
  ansible.builtin.set_fact:
    cacheable: false
    nfc_role_netbox_kubernetes_database_user: |-
      {%- if lookup('env', 'POSTGRES_USER') -%}
        {{ lookup('env', 'POSTGRES_USER') }}
      {%- else -%}
      {{ nfc_role_netbox_kubernetes_database_user }}
      {%- endif %}
    nfc_role_netbox_kubernetes_database_password: |-
      {%- if lookup('env', 'POSTGRES_PASSWORD') -%}
        {{ lookup('env', 'POSTGRES_PASSWORD') }}
      {%- else -%}
        {{ nfc_role_netbox_kubernetes_database_password }}
      {%- endif %}
    nfc_role_netbox_kubernetes_database_host: |-
      {%- if lookup('env', 'POSTGRES_HOST') -%}
       {{  lookup('env', 'POSTGRES_HOST') }}
      {%- else -%}
        {{ nfc_role_netbox_kubernetes_database_host }}
      {%- endif %}
    nfc_role_netbox_kubernetes_database_port: |-
      {%- if lookup('env', 'POSTGRES_PORT') -%}
        {{ lookup('env', 'POSTGRES_PORT') }}
      {%- else -%}
        {{ nfc_role_netbox_kubernetes_database_port }}
      {%- endif %}
  no_log: >
    {%- if not nfc_pb_netbox_force_logging | default(false) -%}
      true
    {%- else -%}
      false
    {%-endif %}


- name: Load Redis Secrets
  ansible.builtin.set_fact:
    cacheable: false
    nfc_role_netbox_kubernetes_redis_host: |-
      {%- if lookup('env', 'REDIS_HOST') -%}
        {{ lookup('env', 'REDIS_HOST') }}
      {%- else -%}
        {{ nfc_role_netbox_kubernetes_redis_host }}
      {%- endif %}
    nfc_role_netbox_kubernetes_redis_port: |-
      {%- if lookup('env', 'REDIS_PORT') -%}
        {{ lookup('env', 'REDIS_PORT') }}
      {%- else -%}
        {{ nfc_role_netbox_kubernetes_redis_port }}
      {%- endif %}
    nfc_role_netbox_kubernetes_redis_username: |-
      {%- if lookup('env', 'REDIS_USER') -%}
        {{ lookup('env', 'REDIS_USER') }}
      {%- else -%}
        {{ nfc_role_netbox_kubernetes_redis_username }}
      {%- endif %}
    nfc_role_netbox_kubernetes_redis_password: |-
      {%- if lookup('env', 'REDIS_PASSWORD') -%}
        {{ lookup('env', 'REDIS_PASSWORD') }}
      {%- else -%}
        {{ nfc_role_netbox_kubernetes_redis_password }}
      {%- endif %}
  no_log: >
    {%- if not nfc_pb_netbox_force_logging | default(false) -%}
      true
    {%- else -%}
      false
    {%-endif %}
