---

nfc_pb_netbox_force_logging: false    # Optional, Boolean. Don't hide sensitive data from logs. Setting this to true will have secrets logged.

# NetBox
nfc_pb_netbox_netbox_token:           # Mandatory, String. Token of user with write permissions
nfc_pb_netbox_netbox_url:             # Mandatory, String. URL of netbox server. including protocol and port if applicable. no trailing `/`

# GLPI
nfc_pb_netbox_glpi_url_glpi:           # Mandatory, String. URL of GLPI server. including protocol and port if applicable. no trailing `/`
nfc_pb_netbox_itam_glpi_app_token:     # Mandatory, String. App Token from GLPI Settings
nfc_pb_netbox_itam_glpi_user_token:    # Mandatory, String. Token of user with write permissions

nfc_role_netbox_glpi_device_status:    # Netbox Default Device Status'
  - Offline
  - Active
  - Planned
  - Staged
  - Failed
  - Inventory
  - Decommissioning
