---

- name: Init GLPI Session
  ansible.builtin.uri:
    url: "{{ nfc_pb_netbox_glpi_url_glpi }}/apirest.php/initSession"
    method: GET
    # body_format: json
    return_content: true
    headers:
      Authorization: "user_token {{ nfc_pb_netbox_itam_glpi_user_token }}"
      App-Token: "{{ nfc_pb_netbox_itam_glpi_app_token }}"
    status_code:
      - 200
  delegate_to: localhost
  register: glpi_session
  no_log: >
    {%- if not nfc_pb_netbox_force_logging | default(false) -%}
      true
    {%- else -%}
      false
    {%-endif %}
