---

- name: Setup GLPI
  block:


    - name: Init GLPI Session
      ansible.builtin.include_tasks:
        file: tasks/glpi/init-session.yaml


    - name: Setup Status
      ansible.builtin.include_tasks:
        file: tasks/glpi/api_create_update.yaml
        apply:
          tags:
            - always
      loop: "{{ nfc_role_netbox_glpi_device_status }}"
      loop_control:
        label: "{{ item }}"
      tags:
        - never
        - setup
      vars:
        field_name: "{{ item }}"
        field_search_entities_id: 0
        item_type: State
        glpi_api_object: {
          "name": "{{ item }}",
          "entities_id": 0,
          "is_recursive": 1,
          "comment": "NetBox Status",
          "states_id": 0,
          "completename": "{{ item }}",
          "is_visible_computer": 1,
          "is_visible_monitor": 0,
          "is_visible_networkequipment": 1,
          "is_visible_peripheral": 0,
          "is_visible_phone": 1,
          "is_visible_printer": 1,
          "is_visible_softwareversion": 0,
          "is_visible_softwarelicense": 0,
          "is_visible_line": 0,
          "is_visible_certificate": 0,
          "is_visible_rack": 0,
          "is_visible_passivedcequipment": 0,
          "is_visible_enclosure": 0,
          "is_visible_pdu": 0,
          "is_visible_cluster": 0,
          "is_visible_contract": 0,
          "is_visible_appliance": 0,
          "is_visible_databaseinstance": 0,
          "is_visible_cable": 0,
          "is_visible_unmanaged": 0
        }


    - name: Fetch Manufacturers from NetBox
      ansible.builtin.uri:
        url: "{{ nfc_pb_netbox_netbox_url }}/api/dcim/manufacturers/"
        method: GET
        body_format: json
        headers:
          Authorization: Token {{ nfc_pb_netbox_netbox_token }}
        status_code:
          - 200
      delegate_to: localhost
      no_log: >
        {%- if not nfc_pb_netbox_force_logging | default(false) -%}
          true
        {%- else -%}
          false
        {%-endif %}
      register: api_get_manufacturers


    - name: Setup Manufacturer(s)
      ansible.builtin.include_tasks:
        file: tasks/glpi/api_create_update.yaml
        apply:
          tags:
            - always
      loop: "{{ api_get_manufacturers.json.results }}"
      loop_control:
        label: "{{ item.name }}"
      tags:
        - never
        - setup
      vars:
        field_name: "{{ item.name }}"
        item_type: Manufacturer
        glpi_api_object: {
          "comment": "NetBox Manufacturer",
        }

  always:


    - name: Kill GLPI Session
      ansible.builtin.include_tasks:
        file: tasks/glpi/kill-session.yaml
