---
- name: Netbox / GLPI
  hosts: |-
    {%- if nfc_pb_host is defined -%}

      {{ nfc_pb_host }}

    {%- else -%}

      {%- if ansible_limit is defined -%}

        {{ ansible_limit }}

      {%- else -%}

        localhost

      {%- endif -%}

    {%- endif %}
  become: false
  gather_facts: false


  tasks:


    - name: Check if vars file exists
      ansible.builtin.stat:
        path: /root/vars.yaml
      become: true
      delegate_to: localhost
      register: metadata_file_vars
      tags:
        - always
      vars:
        ansible_connection: local


    - name: Load vars file
      ansible.builtin.include_vars:
        file: /root/vars.yaml
      no_log: >
        {%- if not nfc_pb_netbox_force_logging | default(false) -%}
          true
        {%- else -%}
          false
        {%-endif %}
      become: true
      delegate_to: localhost
      vars:
        ansible_connection: local
      when: >
        metadata_file_vars.stat.exists
          and
        nfc_pb_netbox_netbox_url is not defined


    - name: NetBox <-> GLPI Setup
      ansible.builtin.include_role:
        name: nofusscomputing.netbox.netbox_glpi
        tasks_from: setup
      tags:
        - never
        - setup
      vars:
        ansible_connection: local
